# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/packages/*"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "fix(deps):"
    groups:
      angular:
        applies-to: version-updates
        patterns:
        - "@angular*"
        update-types:
        - "minor"
        - "patch"
      typescript-eslint:
        applies-to: version-updates
        patterns:
          - "@typescript-eslint*"
          - "typescript-eslint"
        update-types:
          - "minor"
          - "patch"
      vue:
        applies-to: version-updates
        patterns:
          - "vue"
          - "vite*"
          - "vite"
          - "vue*"
        update-types:
          - "minor"
          - "patch"
      vitest:
        applies-to: version-updates
        patterns:
          - "@vitest*"
          - "vitest"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
