name: Publish
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write # for checkout and tag
  pull-requests: write  # for comments
  packages: write # for publish

jobs:
  run-linter-workflow:
    uses: lukaVarga/skeletonizer/.github/workflows/lint-runner.yml@main
    secrets: inherit
  run-tests-workflow:
    uses: lukaVarga/skeletonizer/.github/workflows/test-runner.yml@main
    secrets: inherit
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [run-linter-workflow, run-tests-workflow]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
      - name: Git Identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Semantic release
        run: npm run semantic-release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
          NPM_TOKEN: ${{ secrets.npm_token }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
