name: Build & run tests

on:
  push:
    branches-ignore:
      - main
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 20
      - name: Build
        run: |
          npm ci
          npm run build
  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 20
      - name: Run tests
        run: |
          npm ci
          npm run build
          npm run coverage
      - name: Archive coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: ./packages/*/coverage
  publish-coverage:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          name: coverage
      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  run-type-check:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 20
      - name: Run type tests
        run: |
          npm ci
          npm run build
          npm run type-check
